zeromq/goczmq

channeler.go, channeler_test.go, goczmq.go, proxy.go, sock.go
* Changed channeler "connect" channel to attachChan - channeler can now work with both bound and connected sockets.  Syntax of endpoint mirrors goczmq's (@ for attach, > for bind, no prefix for default)
Note: while I was refactoring I noticed channeler used some golang reserved words like "error" for channel names which made the code a little difficult to read - so I reworked the names of a few variables while making changes.
Second Note: Having a custom "Type" for socket types instead of just using ints was providing no value and was potentially confusing, so I changed the socket types to go ints.
=> Problem: Channeler can Connect but not Bind

.travis.yml, auth_test.go
Solution: update .travis.yml to use go 1.4
Additional: tweaked timeout period on poller.Wait in auth test to wait a little longer, as was causing a failure in some environments.
=> Problem: goczmq does not use latest go version for travis ci

GODOC.md, auth_test.go, channeler.go, channeler_test.go, cmd/examples/weatherUpdate/wuclient/wuclient.go, cmd/examples/weatherUpdate/wuserver/wuserver.go, cmd/multiperf/multiperf.go, cmd/perf/perf.go, poller_test.go, proxy_test.go, sock.go, sock_test.go
Danger, Will Robinson!  Breaking Changes!
* Get rid of various "String" functions that translate from []byte to string, as translation is simple in go. These functions were solving hypothetical problems.  
* "Frame" in the API terms is now considered to be a []byte
* "Message" in the API terms is now considered to be a [][]byte
* Got rid of various different ways of sending and receiving single message parts and multi-part message, reduced to SendFrame, SendMessage, RecvFrame, RecvMessage
* Refactored all tests appropriately
=> Problem: Send / Recv API is confusing and some problems solved are only hypothetical

sock.go, sock_test.go
Solution: Add RecvFrameNoWait in addition to RecvMessageNoWait
Also: Tests, and slight function order cleanup in sock.go
=> Problem: Checking for a waiting frame is inelegant

sock.go, sock_test.go
Solution: add a length check to the []byte array passed to SendFrame and handle properly.  This lets us send empty frames, which ZMTP supports.
=> Problem: trying to send empty frame causes index error

GODOC.md, sock.go, sock_test.go
Solution: implement io.Reader and io.Writer for Sock
Note: when used with a ROUTER socket, the details of the identity frame are hidden from the user.  If using a strict request / reply model over DEALER / ROUTER, everything concerning the id frame is handled for you.
If you need to do asycnronous handling, Sock now provides GetLastClientID and SetLastClientID methods for getting id that was provided by the id frame, without having to mess with frames.
=> Problem: go developers love their standard interfaces

auth.go, beacon.go, cert.go, goczmq.go, gossip.go, poller.go, proxy.go, sock.go
Solution: 
* remove #cgo tags from all files except goczmq.go
* Accommodate dependencies for static builds in pkg-config
* Remove hardcoded paths and -l flags, we can just trust pkg-config to do the right thing (And it can be configured to point to /usr/local/lib exclusively if necessary)
=> Problem: #cgo tags are duplicated, static builds are not possible

sock.go
Solution: Rename our calls to the renamed methods
=> Problem: goczmq no longer compiles due to czmq function rename

README.md
* Remove redundant info - installation section covers it
By the way - don't know what happened to my git config but I pushed a couple of minor commits to zeromq/goczmq instead of taotetek/goczmq by accident - sorry about that!
=> Problem: README has redundant info

README.md
=> Problem: accidently removed zmq4 shout out when cleaning up README

README.md, auth_test.go, beacon_test.go, channeler.go, channeler_test.go, cmd/examples/weatherUpdate/wuclient/wuclient.go, cmd/examples/weatherUpdate/wuserver/wuserver.go, cmd/multiperf/multiperf.go, cmd/perf/perf.go, goczmq.go, gossip.go, gossip_test.go, poller.go, poller_test.go, proxy.go, proxy_test.go, sock.go, sock_option.go, sock_option_test.go, sock_option_test.gsl, sock_test.go, sockopts.xml
All caps identifiers for some constants and functions did not follow go naming conventions, making code weird to read for go developers.  This pull request fixes that in preparation for our stable release.
Please note that this is a non backwards compatible change.  Apologies for that but Luna and I discussed it - the refactor is easy (simple renaming some things) and is worth the cost.
We are targeting "stable" to be declared to coincide with the CZMQ 3.0 release.  This PR should be the last breaking change to prepare for that.
=> Problem: We did not follow go naming conventions

channeler.go
Closing is now safe to call early as the GC cannot doubletrigger it. It can also be called twice directly without causing a panic, though that is still not recommended
=> Add a CAS guard when closing the channeler

sock_test.go
It appears that sometimes the libzmq layer is not completely finished destroying a socket from one test before the next test starts.  This sometimes results in hung tests when two tests use the same inproc endpoint names.
Changing the inproc endpoint names to be test specific mitigates this issue.  More work will be done to figure out exactly how this occurs.
=> Problem: potential race condition in tests

channeler.go, channeler_test.go, goczmq.go
Solution: Rework the channeler.  Channelers are now constructed by constructors similar to the "smart" socket constructors.  ZeroMQ sockets (and the related poller) are all created in the goroutine they are used in.  This is all similar in ways to a zactor from ZeroMQ, with an additional "hop" for commands from go channels to the command pipe.  This allows us to use the channeler in other channel select loops easily.
The extra "hop' for outbound messages does introduce a performance penalty over using sockets directly (around 4x), but there is future work that can be done to improve this.
=> Problem: channeler implementation used sockets unsafely across threads

channeler_test.go
Solution: add a little randomness to endpoint name
=> Problem: channeler benchmark sometimes fails due to already bound endpoint

poller.go, poller_test.go
This hopefully provides a better report than the previous behavior.
The previous behavior of Wait()-after-Destroy() causes C.zpoller_wait()
to be invoked with a now-null pointer and causes libczmq (or libzmq?) to
segfault.
Fixes #145
=> Panic if Wait() is called after Destroy()

certstore.go, certstore_test.go
Prior behavior was that Lookup returned a Cert regardless of the
successful lookup. This caused a crash when doing things like this:
cert := store.Lookup("nosuchclientkeything")
cert.Print() // Crashed
Adds tests to cover the new behavior. No API change was made, just
behavioral change.
=> CertStore.Lookup now returns nil if no cert is found.

goczmq.go
Solution: Expose the major and minor version constants for ZMQ and CZMQ.
=> Problem: we can't see what versions of ZeroMQ and CZMQ we are on

.travis.yml, beacon.go, beacon_test.go
Details: See https://github.com/zeromq/goczmq/issues/151
Solution: Fix beacon to return address and beacon as single message
Note: this does change the return type of (b *Beacon) Recv(timeout int) from string to [][]byte.  In this case I believe the fix warrants this change as the original Recv call didn't match the Beacon implementation in CZMQ.
=> Problem: Beacon should return address and beacon as single message

gossip_test.go, poller_test.go, sock_test.go
Some tests created sockets without calling Destroy() on them to clean up.  This created dangling sockets and blocked clean clean up of CZMQ contexts.  This PR adds Destroy() calls to properly clean up these dangling sockets.
=> Problem: some tests left dangling sockets and contexts

AUTHORS, cert.go
zcert_set_meta returns void, so do the same in Set_meta
=> returns void from Set_meta; fixes #158

goczmq.go, poller.go, poller_test.go, sock.go
Solution: fix up the cases where errors were being constructed in line by errors.New or fmt.Errorf by making them defined errors in goczmq.go.  This PR also fixes some linting problems for uncommented exported variables.
=> Problem: construction of errors was a bit sloppy

sock.go, sock_test.go
This PR partially addresses https://github.com/zeromq/goczmq/issues/157 .
Read now returns the number of bytes read into the supplied byte array (p) properly.  In cases where p is too small to contain the full message, Read will return ErrSliceFull if p is too small to hold the message.  This is less than ideal - but the scope of changes required to allow multiple Read calls to consume a single message are much larger, as we would need to cache the frame between calls which we currently do not do.
So, for now we will fix Read to return the correct number of bytes, and to send a clear error message as to why Read is failing if p is too small.
=> Problem: sock.Read should return read number of bytes not size of frames

sock_test.go
Solution: fix it! Just a one line change to pass golint.  We like to pass golint, because attention to detail is important.
=> Problem: sock_test.go did not pass golint

readwriter.go, readwriter_test.go, sock.go
Solution: Create goczmq.ReadWriter, which will provide a more sophisticated io.ReadWriter interface that will handle this situation correctly while not breaking backwards compatibility.
This initial PR does the following:
* Adds goczmq.ReadWriter, which currently has the same limitations as sock.Read
* Marks sock.Read and sock.Write as DEPRECATED in the documentation. We will not remove these as we might break existing code that depends on goczmq
This gives us a place to make changes and go forward with solving this problem, while not breaking any existing API calls.  My plan is to add a buffer to ReadWriter that will allow Read to properly handle returning parts of a frame sequentially, so that multiple calls to ReadWriter.Read with a buffer smaller than a frame will do the right thing, …
=> Problem: Sock io.ReadWriter cannot handle len(p) < len(Frame)

goczmq.go, readwriter.go, readwriter_test.go
This PR finishes the initial support for ReadWriter.Read working with buffers that are smaller than the zmq message size.  Now, ReadWriter will cache the most recently read message until Read has been called enough times to read the entire message, at which point it will fetch the next message off the socket.
In the case of reading off of a ZMQ_ROUTER socket, the identity from the identity frame is read and held, and is accessible via GetLastCliendID.  SetLastClientID can be used to set the intended target for a Write call.
Note that this does not support multi part messages other than supporting identity frames when reading from a ZMQ_ROUTER socket.  This is intentional.  Read will return ErrMultiPartUnsupported when encountering a multi part message, defined as "a message with more than …
=> Problem: ReadWriter.Read cannot handle len(p) < len(Frame)

readwriter.go, readwriter_test.go
ReadWriter should return an ErrMultiPartUnsupported when:
* The socket is any socket other than Router, and a received message has 2 or more parts.
* The socket is a Router, and a received message has 3 or more parts.
This PR fixes a bug in this logic and adds a test to ensure it is fixed.
=> Problem: ReadWriter should return error on multi-part message

readwriter_test.go, sock_test.go
Having benchmarks for code we are deprecating isn't useful - as the first step towards deprecating sock.Read and sock.Write in favor of ReadWriter.Read and ReadWriter.Write, let's get rid of the benchmark tests for sock.Read / Sock.Write.
=> Problem: maintaining code that is not useful is not useful

goczmq.go, readwriter.go, readwriter_test.go
ZeroMQ does not expose transport disconnect information.  For instance, there is no way to detect when a client disconnects from a server at the transport level. In cases where knowledge of the number of clients is desired, this functionality is delegated to the application level.  Because of this, using io.EOF to denote when a "stream" has closed when reading from a socket is not possible.
ZeroMQ does have the concept of atomic messages, rather than a stream. In cases where we are reading a message where the message is larger than our read buffer, returning an io.EOF when the entirety of the message is read lets us use ReadWriter.Read and properly deal with messages.
So,. this PR changes ReadWriter.Read to return an io.EOF when reaching the end of a message, and changes a timeout on …
=> Problem: io.EOF semantics did not make sense

cert.go, cert_test.go, goczmq.go
**Test output before fix**
```
dhanush@Indradhanushs-MacBook-Pro:~/golang/src/github.com/zeromq/goczmq$ go test -run NewCertFromFile
--- FAIL: TestNewCertFromFile (0.00s)
cert_test.go:71: want &goczmq.Cert{zcertT:(*goczmq._Ctype_struct__zcert_t)(nil)}, have <nil>
FAIL
exit status 1
FAIL    github.com/zeromq/goczmq        0.015s
```
**Test output after fix**
```
dhanush@Indradhanushs-MacBook-Pro:~/golang/src/github.com/zeromq/goczmq$ go test -run NewCertFromFile
PASS
ok  	github.com/zeromq/goczmq	0.015s
```
=> Problem: NewCertFromFile has no sanity check on filename.

goczmq.go, sock.go, sock_test.go
**Test output before fix:**
```
dhanush@Indradhanushs-MacBook-Pro:~/golang/src/github.com/zeromq/goczmq$ go test -run TestRecvFrameCalledAfterDestroy
Assertion failed: (source), function zframe_recv, file src/zframe.c, line 116.
SIGABRT: abort
PC=0x7fff8f55f866 m=0
signal arrived during cgo execution
goroutine 20 [syscall, locked to thread]:
runtime.cgocall(0x40029b0, 0xc8200235a8, 0x0)
/usr/local/go/src/runtime/cgocall.go:120 +0x11b fp=0xc820023578 sp=0xc820023548
github.com/zeromq/goczmq._Cfunc_zframe_recv(0x0, 0x0)
github.com/zeromq/goczmq/_test/_obj_test/_cgo_gotypes.go:543 +0x36 fp=0xc8200235a8 sp=0xc820023578
github.com/zeromq/goczmq.(*Sock).RecvFrame(0xc82006d6c0, 0x0, 0x0, 0x0, 0xc820070b01, 0x0, 0x0)
/Users/dhanush/golang/src/github.com/zeromq/goczmq/sock.go:267 +0x66 …
```
=> Problem: RecvFrame goes all bonkers if invoked after socket has been destroyed

auth_test.go
The auth example code used inproc sockets - which don't support curve, so the example was a bit misleading.
=> Problem: auth example used inproc

cert.go
Solution: update Set_meta to call zcert_set_meta with a format string for value so that we don't get a warning.
=> Problem: Set_meta in cert producing compiler warning

README.md
Solution: move to using gopkg.in to provide stable release urls.
=> Problem: we want to move forward on new socket types

channeler.go
New czmq sockets are created concurrently when creating a channel.
This may lead to a crash when initializing the CZMQ context the first time:
src/zsys.c:179: zsys_init: Assertion `!s_process_ctx' failed.
To solve this concurrency issue, initialize the CZMQ context earlier in the main thread
=> Problem: TestPushPullChanneler randomly fails (crash)

.travis.yml, sock.go
Solution: write a wrapper function so that we can cross the go <-> c barrier one less time.  This shaves a couple hundred nanoseconds off the call.
Note: also updates travis to use Go 1.7 for tests.
=> Problem: SendFrame could make fewer cgo calls

sock.go
[`C.CString`](https://golang.org/src/cmd/cgo/out.go?#L1421) will create a 1 byte buffer when passed an empty string. `Sock.SendFrame` is currently doing this when `data` is of zero length. The buffer created is never freed, and thus will leak.
=> Sock.SendFrame leaks a 1 byte pointer when data length is zero

channeler.go, channeler_test.go
the channeler variants of the subscriber socket can't handle subscribe/unsubscribe during runtime. the subscriptions are done when the socket/channeler is instantiated and can't be changed later.
i added 2 functions to change subscriptions during socket lifetime.
comments welcome.
=> added subscribe/unsubscribe functions

channeler.go
Solution: change return type of context init to void.
=> Problem: channeler had non void function with no return

channeler.go, channeler_test.go
Reference: https://github.com/zeromq/goczmq/issues/225
Solution: Change NewSubChanneler to accept a variadic list of strings for topics and change Channeler.subscribe from a string to a *string. Now if no topics are passed to the constructor, Channeler.subscribe will be nil and the Channeler will start with no subscriptions. 
A list of topics  can be passed, and to keep backwards compatibility, a single comma delimited string will still work.
=> Problem: cannot make unsubscribed SubChanneler

goczmq.go
Solution: add -DZMQ_BUILD_DRAFT_API flag to cgo windows flags. See: https://github.com/zeromq/goczmq/issues/224
=> Problem: scatter-gather did not work on windows

goczmq.go, sock.go, sock_draft.go, sock_draft_test.go, sock_test.go
Solution: move code  that depends on DRAFT features of zmq to separate files with draft build tag. These files will then not build by default. Users wishing to build against a czmq with draft enabled can pass "-tags draft" to go build.
=> Problem: ubuntu has zmq packages without draft enabled

beacon_test.go
Solution: check if returned message is valid length before calling test log command
=> Problem: beacon test doesnt work on travis

beacon_test.go
Solution: fix ExampleBeacon to not take an argument.
=> Problem: ExampleBeacon should be niladic

auth_test.go, channeler.go, sock.go, sock_option.go, sock_option.gsl, sock_option_test.go, sock_option_test.gsl, sockopts.xml
The growing list of socket option functions, when attached to the sock struct, presents a large API surface area which makes programming unfriendly.  As a solution, we move the options to use functional arguments. This allows us to pass a list of options to set to the NewSock constructor at socket creation time, while keeping the API of Sock itself small.
Since this will eventually be a backwards incompatible change, I have released a new 4.x release of goczmq today. The deprecation of the old option methods will happen in a new major release.
=> Problem: sock API surface area too large due to option setters

README.md
Documentation states that the code will work with CZMQ 4.x+ However, this does not seem to be the case.
```json
{                                                               
"checksumSHA1": "nnlv7YDAEQZv0XMm4CMgMaJJnAA=",         
"path": "gopkg.in/zeromq/goczmq.v4",                    
"revision": "98ab09146269d98bc3e427046f5fc222c4134e0b", 
"revisionTime": "2017-10-08T14:05:00Z"                  
}  
```
```json
{                                                               
"checksumSHA1": "7Y/ABorbMzLNU3sNoK3/nPtgcVU=",         
"path": "github.com/zeromq/goczmq",                     
"revision": "a3998524f7fcd7fab479e485fa2ae3b02bcf6cac", 
"revisionTime": "2017-11-11T20:18:50Z"                  
}
```
```
$ rpm -qa | grep zmq
cppzmq-devel-4.1.6-2.fc26.x86_64 …
```
=> Problem: CZMQ 4.2 is required, not just 4.0+

channeler.go
This is meant to address #135, among other things (there are other options you might want to set on a Channeler's socket). I'm not sure if it's really a complete solution (there are some options that it makes sense to set post-creation) but it's better than nothing.
It adds a `...SockOption` parameter to most of the Channeler constructors, except for `NewSubChanneler` which already had a `...string` parameter for the subscriptions list — this becomes a `...interface{}` which can contain subscriptions *or* `SockOption`s, identified by their type. This isn't entirely pretty, but it avoids breaking the API.
I would have liked to write some tests for these changes, but since the socket is a local variable to the actor method, it's fairly difficult to detect whether an option has been set, …
=> Allow passing SockOptions to Channeler constructors

auth_test.go, channeler.go, channeler_test.go, goczmq.go, poller.go, poller_test.go, readwriter.go, sock.go, test_utils.go
Currently, calls to panic() are used to communiate errors. Doing this
from goroutines makes it impossible to recover from the panics, which
effectively forces the program to exit.
Fix this by replacing panic() calls with a new error channel to
communicate errors back to caller.
Resolves #242. Comments?
=> Fix #242: Unable to recover from panics when creating new Channeler

channeler.go
see https://github.com/zeromq/goczmq/issues/252
Use unique ids returned by czmq library instead of random numbers
to build unique inproc addresses in function newChanneler
=> Problem: potential reuse of inproc address

sock_option.go, sock_option.gsl, sock_option_test.go, sock_option_test.gsl
The old socket option interface was inflexible due to having to add new functions directly to *Sock to expand it, cluttering the Sock API with a lot of optional and often not used functions. Awhile back, I created a new function args API and marked the old API deprecated. In preparation for a new release of GoCZMQ I'm not removing the deprecated API.
=> Problem: old sock option api was deprecated

go.mod, go.sum, proxy.go, proxy_test.go
CURVE support for the underlying zproxy.
This mirrors the API in the underlying czmq library. I'm happy to switch things around wrt naming/semantics and add more tests if required.
=> CURVE support for Proxy

monitor.go, monitor_test.go
This is a wrapper for the czmq zmonitor actor. It allows listening for some events that otherwise might be impossible to receive. Includes minimal API needed to create and destroy the actor.
=> Monitor actor for obtaining socket events

goczmq.go, sock.go
Solution: retry functions that are likely to fail with EINTR
This relates to [changes made in Go 1.14](https://golang.org/doc/go1.14#runtime) but also applies to 1.15.
Example applications that fail only without the patch (note that although these will definitely fail on both 1.14 and 1.15 it happens very quickly with 1.14 while it can take several minutes on 1.15)
pub.go:
```go
package main
import (
"time"
"github.com/zeromq/goczmq/v4"
)
func main() {
c := goczmq.NewPubChanneler("@tcp://*:20001")
defer c.Destroy()
t := time.NewTicker(1 * time.Nanosecond)
for {
select {
case err := <-c.ErrChan:
panic(err)
case <-t.C:
c.SendChan <- [][]byte{[]byte("X"), []byte("OK")}
}
}
}
```
sub.go
```go
package main
import (
"github.com/zeromq/goczmq/v4"
)
func main() {
c := …
```
=> Problem: socket interactions randomly fail due to EINTR

sock.go, sock_test.go
Solution: fix bitmask match against ZMQ_EVENTS
This fixes https://github.com/zeromq/goczmq/issues/266
Basically current `Pollin`/`Pollout` implementation returns false negatives if multiple events are present at the same time, this is a common situation with Router socket.
=> Problem: Pollin()/Pollout() misbehave with Router socket

poller.go
The following
```poller, err := zmq.NewPoller(nil)```
generates
```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x52ff5f]
```
at line 37 in `poller.go`.
This PR simply checks for nil as an argument for `NewPoller`.
=> Fix issue with creater a poller with nil readers

channeler.go
Solution: keep goroutine running to allow graceful shutdown
Currently if any error is returned by ZMQ calls made inside the Channeler `actor` goroutine it triggers an immediate exit of the that goroutine. This makes it impossible to shut down the companion `channeler` goroutine (and allow it to free its allocated resources) because the only path for doing so is sending `"destroy"` to `commandChan` which then causes the `channeler` goroutine to block forever waiting for a response to the "destroy" command from a now missing `actor` goroutine here: https://github.com/zeromq/goczmq/blob/4dc887d7239b715e613e2937d5aaf58d2033c8b0/channeler.go#L205
The proposed solution keeps the `actor` goroutine working and hopefully able to receive and process the `"destroy"` command even after returning an …
=> Problem: actor errors block channeler shutdown

proxy_test.go, sock_option.go, sock_option_test.go, sockopts.xml
This exposes the ZMQ_ROUTER_NOTIFY option for goczmq users.
It's a draft option but hopefully it's ok to follow the czmq convention of having draft options setters be no-ops when the libzmq build hasn't enabled drafts (as is the case for `zsock_set_router_notify` [here](https://github.com/zeromq/czmq/blob/06441e529c758e1ce410f22d10d95e42cc991cb5/src/zsock_option.inc#L425))
=> Problem: ZMQ_ROUTER_NOTIFY not supported

monitor.go
Solution: retry zmonitor commands in case of EINTR failures
Same fix as https://github.com/zeromq/goczmq/pull/285 for commands sent to `zmonitor` actor which internally rely on `zstr_sendx` function calls that need to be retried in case of EINTR error.
=> Problem: sending commands to zmonitor actor can fail with EINTR

CONTRIBUTING.md, certstore.go, certstore_test.go
While trying to use CertStore, I found that using czmq's in-memory zcertstore wasn't possible through goczmq. Here's a small patch to add that functionality along with a subset of the main certstore tests.
=> Add in-memory CertStore support
