channeler.go

* Underlying C zsock_attach function already had logic I included in channeler.go - simplifying.

Problem: logic duplication in channeler due to not enough coffee

---

sock.go
sock_test.go

Solution: add SendMultiBytes, SendMultiString, RecvMultiBytes, and RecveMultiString functions to make working with []byte and string based multi part messages simpler

Problem: Sending and receiving multi part string and []byte messages is awkward

---

GODOC.md
cmd/multiperf/multiperf.go
cmd/perf/perf.go

Solution: fix import paths in perf tests.
Secondary: updated auto generated GODOC.md

Problem: perf tests had bad import path

---

README.md

Problem: example had ZBeacon instead of Beacon

---

zgossip/msg/GODOC.md
zgossip/msg/hello.go
zgossip/msg/hello_test.go
zgossip/msg/invalid.go
zgossip/msg/invalid_test.go
zgossip/msg/msg.go
zgossip/msg/ping.go
zgossip/msg/ping_test.go
zgossip/msg/pong.go
zgossip/msg/pong_test.go
zgossip/msg/publish.go
zgossip/msg/publish_test.go
zgossip_msg.bnf
zgossip_msg.xml

* Added zgossip_msg.xml definition of zgossip messages
* Now uses zproto's templates so no need for a custom gsl for go in this repo
* Generated zgossip message classes

Problem: we want to finish implementing zgossip

---

gossip.go
gossip_test.go

* Implemented the rest of the gossip API other than the STATUS command
* STATUS will follow in another pull request once it is done.

Problem: gossip support isn't finished

---

iochunk.xml
iochunk/msg/chunk.go
iochunk/msg/chunk_test.go
iochunk/msg/msg.go

Solution: add an iochunk zproto message type so we can move chunker to use it.

Problem: chunker uses multi frame messages which is slower and more complex

---

channeler.go
goczmq.go
sock.go

Solution: change Flag to an int.

Problem: explicit Flag type gets in the way and adds nothing of use

---

sock_test.go

* Add testable example to sock_test.go

Problem: We don't have enough example code

---

beacon_test.go

* Added example to beacon 
* Added addition check to beacon test to ensure payload delivered

Problem: We still need more examples

---

beacon_test.go

* remove test that does not work on travis for now

Problem: some udp related tests do not work on travis

---

auth.go
beacon.go
cert.go
gossip.go
poller.go
proxy.go
sock.go

* Added better documentation to each type.

Problem: documentation could be better.

---

AUTHORS
goczmq.go

* Improved package description
* Aded Indradhanush Gupta to AUTHORS file

Problem: package description needed work

---

beacon.go
gossip_test.go
poller_test.go
proxy_test.go

* Fix the names
* Also changed the beacon reference to b *Beacon from z *Beacon

Problem: named a couple of examples incorrectly

---

sock_test.go

Solution: add benchmark tests for SendFrame

Problem: if we want to maintain or improve performance we need measurements

---

sock_test.go

Solution: removing it for the sake of simplicity even though it was cool :(
( ;) @PSG-Luna  )

Problem: sync pool is not really needed for the benchmark test

---

certstore.go
certstore_test.go

Solution: add certstore for working with zeromq curve certificate directories.

Problem: we do not support zcertstore API

---

proxy_test.go
sock_test.go

* Add benchmark for proxy
* Better naming for sock benchmarks

Problem: still not benchmarking ALL the things.

---

poller_test.go
sock_test.go

* Added benchmark for receive with Poller
* Added benchmark for ReadWriter

Problem: no benchmarks for Poller use or ReadWriter interface

---

channeler_test.go

Solution: added benchmark for channeler

Problem: need benchmark for channeler so we can improve channeler

---

auth_test.go
beacon_test.go
cert_test.go
gossip_test.go
proxy_test.go

Solution: change tests of czmq actors to only set verbose if go test verbose flag is set.

Problem: tests are very noisey on stdout

---

sock.go
sock_test.go

Solution: 
* change error return 
* add tests to prove and ensure it works

Problem: sock ReaderWrite implementation didn't work with encode / decode

---

sock_test.go

* add a benchmark for using encode / decode with ReadWriter interface
* remove redundant tests left over from figuring some things out

Problem: encode / decode is not measured

---

sock.go

Solution:  Change the last id cache in the sock struct to be a slice of strings that is treated as a FIFO queue.  Now, when a set of mesages is read via sock.Read from a router socket, when a reply is sent back it will use the id of the first message received since the last time the router sent a reply.  This allows a router to read multiple incoming messages via sock.Read and then send multiple replies via sock.Write while still keeping routing frame management hidden so the API user does not have to be concerned with it.
Note: ReadFrame / ReadMessage calls do not use this, and in the case of router sockets still expect the API user to understand routing frames and their usage.

Problem: ReadWriter with Dealer / Router only works with request / reply lockstep

---

channeler.go
channeler_test.go
sock_test.go

* Added example for channeler
* Cleaned up channeler formatting a little
* Added a few comments to sock example

Problem: channeler has no documentation example

---

README.md

Problem: the README doesn't show the various interfaces

---

README.md

change bind to connected for dealer socket in README

Problem: README says "bound" in a spot it should say "connected"

---

README.md

Problem: minor grammar problems in README

---

README.md

Solution: Update the README instructions, and declare a stable release (yay!)

Problem: README does not cover zeromq and czmq stable releases

---

README.md

* Fix minor issue in build instructions for libsodium

Problem: minor error in install documenation

---

goczmq.go

This let me compile for windows. fixes #137

working compile for windows

---

AUTHORS

Problem: Ben made a code contribution, he should be in the AUTHORS file

---

poller.go
poller_test.go

See: https://github.com/zeromq/goczmq/issues/141
Solution: modified poller_new to allow construction of poller with no sockets as allowed by the underlying czmq poller.  Added test to verify it all works.

 Problem: Poller constructor requires at least one socket. 

---

poller_test.go

Solution: use different inproc address for new poller test

Problem: new poller test uses already used inproc address sometimes causing panic

---

AUTHORS

Solution: Add Jordan to the Authors list :)

Problem: Jordan contributed a patch and isn't in the authors list!

---

beacon.go

Problem: Beacon Recv was needlessly complicated 

---

channeler_test.go
poller_test.go
proxy_test.go
sock_test.go

Solution: modify benchmarks to include throughput figures

Problem: we do not measure throughput in benchmark tests

---

sock.go

Problem: commented out code is confusing

---

CONTRIBUTING.md

Problem: CONTRIBUTING.md was lacking a bit

---

readwriter.go
readwriter_test.go

Solution: add ReadWriter.SetTimeout.  Now, a timeout can be set on ReadWriter in milliseconds. When a Read call blocks for longer than the timeout, it will return an io.EOF.

Problem: ReadWriter.Read can block forever

---

readwriter.go

Problem: ReadWriter had an unecessary call to poller

---

readwriter_test.go

Solution: Add benchmark tests for ReadWriter.

Problem: We do not know the performance of ReadWriter

---

auth_test.go
beacon_test.go
cert_test.go
channeler_test.go
gossip_test.go
poller_test.go
proxy_test.go
readwriter_test.go
sock_test.go

This PR cleans up *_test files to use more consistent idioms in each test case.  This makes the tests more consistent across classes and makes them cleaner and easier to read.

Problem: test code was idiomaticly inconsistent and hard to read

---

auth_test.go
cert_test.go
certstore_test.go
poller_test.go
proxy_test.go
readwriter_test.go
sock_test.go

Solution: Clean up the test code more.

Problem: test code was still inconsistent

---

auth.go
beacon.go
gossip.go
proxy.go

Solution: add frees for some C.CStrings.
Addresses https://github.com/zeromq/goczmq/issues/181

Problem: actor interfaces were leaking strings

---

auth.go
beacon.go
cert.go
certstore.go
gossip.go
proxy.go
sock.go
sock_option.go
sock_option.gsl

Solution: properly handle and free strings created by CString

Problem: we were leaking some c strings

---

cert.go
gossip.go

Problem: found a couple more unfreed c strings

---

channeler.go

Solution: Modify channeler to remove subscription option from NewXsubChanneler.

Problem: XSub does not accept subscription options

---

beacon.go

In a current project, I am required to publish binary data in the beacon. This binary data contains zeros part-way through and so Go/C/czmq is truncating the string at the first zero it comes to.
Solution: (1) Add a new `PublishBytes` method to allow publishing a byte slice, with no conversion to strings at any point. (2) Modify `Recv` to read C byte arrays instead of strings then use to fill Go byte slices.
A similar modification could also be done to the `Subscribe` method but this is not required by me at the moment.

Problem: Publish and Recv in beacon.go assume strings

---

cmd/examples/weatherUpdate/wuclient/wuclient.go
cmd/examples/weatherUpdate/wuserver/wuserver.go
cmd/goczmq-certgen/goczmq-certgen.go
cmd/multiperf/multiperf.go
cmd/perf/perf.go

This PR changes the cmd/* programs to use gopkg.in for their imports.

Problem: we want to use gopkg.in for managing versions

---

AUTHORS

Problem: we have contributors who should be added to AUTHORS

---

goczmq.go

Checked w/ lint, vet, and fmt.

expose zsys layer shutdown; fixes #204

---

.travis.yml

Problem: we want to test with go 1.7.1

---

goczmq.go

Problem: A request.

---

README.md
cert.go
cmd/examples/weatherUpdate/wuclient/wuclient.go
cmd/examples/weatherUpdate/wuserver/wuserver.go
cmd/goczmq-certgen/goczmq-certgen.go
cmd/multiperf/multiperf.go
cmd/perf/perf.go

Solution: update API to be compatible with latest stable CZMQ

Problem: new czmq release

---

README.md

Problem: README had no install instructions

---

sock.go

Solution: fix call to sendframe

Problem: sendframe signature changed

---

goczmq.go
sock.go
sock_test.go

* Adds support for ZMQ_SCATTER and ZMQ_GATHER thread safe sockets.

Problem: we want ZMQ_SCATTER / ZMQ_GATHER support

---

README.md

Update version  info in readme.

Problem: README out of date

---

sock_option.go
sock_option_test.go
sock_option_test.gsl
sockopts.xml

* Adds sock options for 4.2 and 4.1.

Problem: want to support new socket options

---

.travis.yml

Solution: use pre-built packages from OBS
~1 minute 10 seconds vs ~5 minutes 30 seconds :-)

Problem: Travis CI slowed down by build-dependencies

---

sock.go

Solution: add support for function options.

Problem: smart constructors do not accept options

---

proxy_test.go
readwriter_test.go
sock_test.go

Solution: clean up a few things

Problem: found some minor code quality issues

---

auth_test.go
beacon_test.go
cert_test.go
certstore_test.go
proxy_test.go
sock_test.go

Problem: have places we do not check error returns

---

.travis.yml

Updates travis build and go version

Problem: travis build was out of date

---

go.mod

Problem: no go mod support

---

cmd/examples/weatherUpdate/wuclient/wuclient.go
cmd/examples/weatherUpdate/wuserver/wuserver.go
cmd/goczmq-certgen/goczmq-certgen.go
cmd/multiperf/multiperf.go
cmd/perf/perf.go
go.mod

all: add proper support for modules

---

channeler_test.go

Solution: fix tests by confirming subscription before sending message
I noticed the tests failed for https://github.com/zeromq/goczmq/pull/286 . Same tests I also saw randomly failing locally. These tests failed because they have a race: they publish a message potentially before a subscription has reached the pub socket.
I solved this by switching to XPub socket and explicitly checking that said socket received the expected amount of subscription messages. This makes the tests solid with repeated `go clean -cache; make test` runs.

Problem: pub/sub channeler tests randomly fail with timeout
